vars:
  token: {{ TOKEN }} # GH App token
  owner: oscal-compass

policy:
  catalogs:
    - OSPS_B
  applicability:
    - Maturity Level 1

write-directory: evaluation_results
services:
  trestle:
    plugin: github-repo
    vars:
      repo: compliance-trestle
  oscal-sdk-go:
    plugin: github-repo
    vars:
      repo: oscal-sdk-go
  c2p:
    plugin: github-repo
    vars:
      repo: compliance-to-policy
  c2p-go:
    plugin: github-repo
    vars:
      repo: compliance-to-policy-go
